/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// GetUserNftTxsResponse model.GetUserNftTxsResponse.description
type GetUserNftTxsResponse struct {
	// field.totalNum.description
	TotalNum int64 `json:"totalNum"`
	// field.GetUserNftTxsResponse.transactions
	Transactions []NftTxData `json:"transactions"`
}

// NewGetUserNftTxsResponse instantiates a new GetUserNftTxsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserNftTxsResponse(totalNum int64, transactions []NftTxData) *GetUserNftTxsResponse {
	this := GetUserNftTxsResponse{}
	this.TotalNum = totalNum
	this.Transactions = transactions
	return &this
}

// NewGetUserNftTxsResponseWithDefaults instantiates a new GetUserNftTxsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserNftTxsResponseWithDefaults() *GetUserNftTxsResponse {
	this := GetUserNftTxsResponse{}
	return &this
}

// GetTotalNum returns the TotalNum field value
func (o *GetUserNftTxsResponse) GetTotalNum() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalNum
}

// GetTotalNumOk returns a tuple with the TotalNum field value
// and a boolean to check if the value has been set.
func (o *GetUserNftTxsResponse) GetTotalNumOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalNum, true
}

// SetTotalNum sets field value
func (o *GetUserNftTxsResponse) SetTotalNum(v int64) {
	o.TotalNum = v
}

// GetTransactions returns the Transactions field value
func (o *GetUserNftTxsResponse) GetTransactions() []NftTxData {
	if o == nil {
		var ret []NftTxData
		return ret
	}

	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value
// and a boolean to check if the value has been set.
func (o *GetUserNftTxsResponse) GetTransactionsOk() ([]NftTxData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transactions, true
}

// SetTransactions sets field value
func (o *GetUserNftTxsResponse) SetTransactions(v []NftTxData) {
	o.Transactions = v
}

func (o GetUserNftTxsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["totalNum"] = o.TotalNum
	}
	if true {
		toSerialize["transactions"] = o.Transactions
	}
	return json.Marshal(toSerialize)
}

type NullableGetUserNftTxsResponse struct {
	value *GetUserNftTxsResponse
	isSet bool
}

func (v NullableGetUserNftTxsResponse) Get() *GetUserNftTxsResponse {
	return v.value
}

func (v *NullableGetUserNftTxsResponse) Set(val *GetUserNftTxsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserNftTxsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserNftTxsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserNftTxsResponse(val *GetUserNftTxsResponse) *NullableGetUserNftTxsResponse {
	return &NullableGetUserNftTxsResponse{value: val, isSet: true}
}

func (v NullableGetUserNftTxsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserNftTxsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
