/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// AmmTransferData struct for AmmTransferData
type AmmTransferData struct {
	Id           int64  `json:"id"`
	TokenId      int32  `json:"tokenId"`
	TokenSymbol  string `json:"tokenSymbol"`
	Amount       string `json:"amount"`
	ActualAmount string `json:"actualAmount"`
	FeeAmount    string `json:"feeAmount"`
}

// NewAmmTransferData instantiates a new AmmTransferData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmmTransferData(id int64, tokenId int32, tokenSymbol string, amount string, actualAmount string, feeAmount string) *AmmTransferData {
	this := AmmTransferData{}
	this.Id = id
	this.TokenId = tokenId
	this.TokenSymbol = tokenSymbol
	this.Amount = amount
	this.ActualAmount = actualAmount
	this.FeeAmount = feeAmount
	return &this
}

// NewAmmTransferDataWithDefaults instantiates a new AmmTransferData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmmTransferDataWithDefaults() *AmmTransferData {
	this := AmmTransferData{}
	return &this
}

// GetId returns the Id field value
func (o *AmmTransferData) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AmmTransferData) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AmmTransferData) SetId(v int64) {
	o.Id = v
}

// GetTokenId returns the TokenId field value
func (o *AmmTransferData) GetTokenId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *AmmTransferData) GetTokenIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *AmmTransferData) SetTokenId(v int32) {
	o.TokenId = v
}

// GetTokenSymbol returns the TokenSymbol field value
func (o *AmmTransferData) GetTokenSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenSymbol
}

// GetTokenSymbolOk returns a tuple with the TokenSymbol field value
// and a boolean to check if the value has been set.
func (o *AmmTransferData) GetTokenSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenSymbol, true
}

// SetTokenSymbol sets field value
func (o *AmmTransferData) SetTokenSymbol(v string) {
	o.TokenSymbol = v
}

// GetAmount returns the Amount field value
func (o *AmmTransferData) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *AmmTransferData) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *AmmTransferData) SetAmount(v string) {
	o.Amount = v
}

// GetActualAmount returns the ActualAmount field value
func (o *AmmTransferData) GetActualAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActualAmount
}

// GetActualAmountOk returns a tuple with the ActualAmount field value
// and a boolean to check if the value has been set.
func (o *AmmTransferData) GetActualAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActualAmount, true
}

// SetActualAmount sets field value
func (o *AmmTransferData) SetActualAmount(v string) {
	o.ActualAmount = v
}

// GetFeeAmount returns the FeeAmount field value
func (o *AmmTransferData) GetFeeAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeeAmount
}

// GetFeeAmountOk returns a tuple with the FeeAmount field value
// and a boolean to check if the value has been set.
func (o *AmmTransferData) GetFeeAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeAmount, true
}

// SetFeeAmount sets field value
func (o *AmmTransferData) SetFeeAmount(v string) {
	o.FeeAmount = v
}

func (o AmmTransferData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["tokenId"] = o.TokenId
	}
	if true {
		toSerialize["tokenSymbol"] = o.TokenSymbol
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["actualAmount"] = o.ActualAmount
	}
	if true {
		toSerialize["feeAmount"] = o.FeeAmount
	}
	return json.Marshal(toSerialize)
}

type NullableAmmTransferData struct {
	value *AmmTransferData
	isSet bool
}

func (v NullableAmmTransferData) Get() *AmmTransferData {
	return v.value
}

func (v *NullableAmmTransferData) Set(val *AmmTransferData) {
	v.value = val
	v.isSet = true
}

func (v NullableAmmTransferData) IsSet() bool {
	return v.isSet
}

func (v *NullableAmmTransferData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmmTransferData(val *AmmTransferData) *NullableAmmTransferData {
	return &NullableAmmTransferData{value: val, isSet: true}
}

func (v NullableAmmTransferData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmmTransferData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
