/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// AmmTransactionData struct for AmmTransactionData
type AmmTransactionData struct {
	Id             int64             `json:"id"`
	Hash           string            `json:"hash"`
	TxHash         string            `json:"txHash"`
	Owner          string            `json:"owner"`
	TxType         string            `json:"txType"`
	TxStatus       string            `json:"txStatus"`
	AmmLayerType   string            `json:"ammLayerType"`
	AmmPoolId      int64             `json:"ammPoolId"`
	AmmPoolAddress string            `json:"ammPoolAddress"`
	LpTokenId      int64             `json:"lpTokenId"`
	LpTokenSymbol  string            `json:"lpTokenSymbol"`
	LpTokenAmount  string            `json:"lpTokenAmount"`
	Transfers      []AmmTransferData `json:"transfers"`
	BlockHeight    int64             `json:"blockHeight"`
	CreatedAt      int64             `json:"createdAt"`
	UpdatedAt      int64             `json:"updatedAt"`
	StorageInfos   []StorageInfo     `json:"storageInfos,omitempty"`
}

// NewAmmTransactionData instantiates a new AmmTransactionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmmTransactionData(id int64, hash string, txHash string, owner string, txType string, txStatus string, ammLayerType string, ammPoolId int64, ammPoolAddress string, lpTokenId int64, lpTokenSymbol string, lpTokenAmount string, transfers []AmmTransferData, blockHeight int64, createdAt int64, updatedAt int64) *AmmTransactionData {
	this := AmmTransactionData{}
	this.Id = id
	this.Hash = hash
	this.TxHash = txHash
	this.Owner = owner
	this.TxType = txType
	this.TxStatus = txStatus
	this.AmmLayerType = ammLayerType
	this.AmmPoolId = ammPoolId
	this.AmmPoolAddress = ammPoolAddress
	this.LpTokenId = lpTokenId
	this.LpTokenSymbol = lpTokenSymbol
	this.LpTokenAmount = lpTokenAmount
	this.Transfers = transfers
	this.BlockHeight = blockHeight
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewAmmTransactionDataWithDefaults instantiates a new AmmTransactionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmmTransactionDataWithDefaults() *AmmTransactionData {
	this := AmmTransactionData{}
	return &this
}

// GetId returns the Id field value
func (o *AmmTransactionData) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AmmTransactionData) SetId(v int64) {
	o.Id = v
}

// GetHash returns the Hash field value
func (o *AmmTransactionData) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *AmmTransactionData) SetHash(v string) {
	o.Hash = v
}

// GetTxHash returns the TxHash field value
func (o *AmmTransactionData) GetTxHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetTxHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxHash, true
}

// SetTxHash sets field value
func (o *AmmTransactionData) SetTxHash(v string) {
	o.TxHash = v
}

// GetOwner returns the Owner field value
func (o *AmmTransactionData) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *AmmTransactionData) SetOwner(v string) {
	o.Owner = v
}

// GetTxType returns the TxType field value
func (o *AmmTransactionData) GetTxType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxType
}

// GetTxTypeOk returns a tuple with the TxType field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetTxTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxType, true
}

// SetTxType sets field value
func (o *AmmTransactionData) SetTxType(v string) {
	o.TxType = v
}

// GetTxStatus returns the TxStatus field value
func (o *AmmTransactionData) GetTxStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxStatus
}

// GetTxStatusOk returns a tuple with the TxStatus field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetTxStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxStatus, true
}

// SetTxStatus sets field value
func (o *AmmTransactionData) SetTxStatus(v string) {
	o.TxStatus = v
}

// GetAmmLayerType returns the AmmLayerType field value
func (o *AmmTransactionData) GetAmmLayerType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmmLayerType
}

// GetAmmLayerTypeOk returns a tuple with the AmmLayerType field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetAmmLayerTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmmLayerType, true
}

// SetAmmLayerType sets field value
func (o *AmmTransactionData) SetAmmLayerType(v string) {
	o.AmmLayerType = v
}

// GetAmmPoolId returns the AmmPoolId field value
func (o *AmmTransactionData) GetAmmPoolId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AmmPoolId
}

// GetAmmPoolIdOk returns a tuple with the AmmPoolId field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetAmmPoolIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmmPoolId, true
}

// SetAmmPoolId sets field value
func (o *AmmTransactionData) SetAmmPoolId(v int64) {
	o.AmmPoolId = v
}

// GetAmmPoolAddress returns the AmmPoolAddress field value
func (o *AmmTransactionData) GetAmmPoolAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmmPoolAddress
}

// GetAmmPoolAddressOk returns a tuple with the AmmPoolAddress field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetAmmPoolAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmmPoolAddress, true
}

// SetAmmPoolAddress sets field value
func (o *AmmTransactionData) SetAmmPoolAddress(v string) {
	o.AmmPoolAddress = v
}

// GetLpTokenId returns the LpTokenId field value
func (o *AmmTransactionData) GetLpTokenId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LpTokenId
}

// GetLpTokenIdOk returns a tuple with the LpTokenId field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetLpTokenIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LpTokenId, true
}

// SetLpTokenId sets field value
func (o *AmmTransactionData) SetLpTokenId(v int64) {
	o.LpTokenId = v
}

// GetLpTokenSymbol returns the LpTokenSymbol field value
func (o *AmmTransactionData) GetLpTokenSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LpTokenSymbol
}

// GetLpTokenSymbolOk returns a tuple with the LpTokenSymbol field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetLpTokenSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LpTokenSymbol, true
}

// SetLpTokenSymbol sets field value
func (o *AmmTransactionData) SetLpTokenSymbol(v string) {
	o.LpTokenSymbol = v
}

// GetLpTokenAmount returns the LpTokenAmount field value
func (o *AmmTransactionData) GetLpTokenAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LpTokenAmount
}

// GetLpTokenAmountOk returns a tuple with the LpTokenAmount field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetLpTokenAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LpTokenAmount, true
}

// SetLpTokenAmount sets field value
func (o *AmmTransactionData) SetLpTokenAmount(v string) {
	o.LpTokenAmount = v
}

// GetTransfers returns the Transfers field value
func (o *AmmTransactionData) GetTransfers() []AmmTransferData {
	if o == nil {
		var ret []AmmTransferData
		return ret
	}

	return o.Transfers
}

// GetTransfersOk returns a tuple with the Transfers field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetTransfersOk() ([]AmmTransferData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transfers, true
}

// SetTransfers sets field value
func (o *AmmTransactionData) SetTransfers(v []AmmTransferData) {
	o.Transfers = v
}

// GetBlockHeight returns the BlockHeight field value
func (o *AmmTransactionData) GetBlockHeight() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.BlockHeight
}

// GetBlockHeightOk returns a tuple with the BlockHeight field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetBlockHeightOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockHeight, true
}

// SetBlockHeight sets field value
func (o *AmmTransactionData) SetBlockHeight(v int64) {
	o.BlockHeight = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AmmTransactionData) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AmmTransactionData) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AmmTransactionData) GetUpdatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetUpdatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AmmTransactionData) SetUpdatedAt(v int64) {
	o.UpdatedAt = v
}

// GetStorageInfos returns the StorageInfos field value if set, zero value otherwise.
func (o *AmmTransactionData) GetStorageInfos() []StorageInfo {
	if o == nil || o.StorageInfos == nil {
		var ret []StorageInfo
		return ret
	}
	return o.StorageInfos
}

// GetStorageInfosOk returns a tuple with the StorageInfos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmmTransactionData) GetStorageInfosOk() ([]StorageInfo, bool) {
	if o == nil || o.StorageInfos == nil {
		return nil, false
	}
	return o.StorageInfos, true
}

// HasStorageInfos returns a boolean if a field has been set.
func (o *AmmTransactionData) HasStorageInfos() bool {
	if o != nil && o.StorageInfos != nil {
		return true
	}

	return false
}

// SetStorageInfos gets a reference to the given []StorageInfo and assigns it to the StorageInfos field.
func (o *AmmTransactionData) SetStorageInfos(v []StorageInfo) {
	o.StorageInfos = v
}

func (o AmmTransactionData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["hash"] = o.Hash
	}
	if true {
		toSerialize["txHash"] = o.TxHash
	}
	if true {
		toSerialize["owner"] = o.Owner
	}
	if true {
		toSerialize["txType"] = o.TxType
	}
	if true {
		toSerialize["txStatus"] = o.TxStatus
	}
	if true {
		toSerialize["ammLayerType"] = o.AmmLayerType
	}
	if true {
		toSerialize["ammPoolId"] = o.AmmPoolId
	}
	if true {
		toSerialize["ammPoolAddress"] = o.AmmPoolAddress
	}
	if true {
		toSerialize["lpTokenId"] = o.LpTokenId
	}
	if true {
		toSerialize["lpTokenSymbol"] = o.LpTokenSymbol
	}
	if true {
		toSerialize["lpTokenAmount"] = o.LpTokenAmount
	}
	if true {
		toSerialize["transfers"] = o.Transfers
	}
	if true {
		toSerialize["blockHeight"] = o.BlockHeight
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.StorageInfos != nil {
		toSerialize["storageInfos"] = o.StorageInfos
	}
	return json.Marshal(toSerialize)
}

type NullableAmmTransactionData struct {
	value *AmmTransactionData
	isSet bool
}

func (v NullableAmmTransactionData) Get() *AmmTransactionData {
	return v.value
}

func (v *NullableAmmTransactionData) Set(val *AmmTransactionData) {
	v.value = val
	v.isSet = true
}

func (v NullableAmmTransactionData) IsSet() bool {
	return v.isSet
}

func (v *NullableAmmTransactionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmmTransactionData(val *AmmTransactionData) *NullableAmmTransactionData {
	return &NullableAmmTransactionData{value: val, isSet: true}
}

func (v NullableAmmTransactionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmmTransactionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
