/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// GetExchangeFeeInfoResponse struct for GetExchangeFeeInfoResponse
type GetExchangeFeeInfoResponse struct {
	ResultInfo ResultInfo                      `json:"resultInfo"`
	Data       *GetExchangeFeeInfoResponseData `json:"data,omitempty"`
}

// NewGetExchangeFeeInfoResponse instantiates a new GetExchangeFeeInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetExchangeFeeInfoResponse(resultInfo ResultInfo) *GetExchangeFeeInfoResponse {
	this := GetExchangeFeeInfoResponse{}
	this.ResultInfo = resultInfo
	return &this
}

// NewGetExchangeFeeInfoResponseWithDefaults instantiates a new GetExchangeFeeInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetExchangeFeeInfoResponseWithDefaults() *GetExchangeFeeInfoResponse {
	this := GetExchangeFeeInfoResponse{}
	return &this
}

// GetResultInfo returns the ResultInfo field value
func (o *GetExchangeFeeInfoResponse) GetResultInfo() ResultInfo {
	if o == nil {
		var ret ResultInfo
		return ret
	}

	return o.ResultInfo
}

// GetResultInfoOk returns a tuple with the ResultInfo field value
// and a boolean to check if the value has been set.
func (o *GetExchangeFeeInfoResponse) GetResultInfoOk() (*ResultInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultInfo, true
}

// SetResultInfo sets field value
func (o *GetExchangeFeeInfoResponse) SetResultInfo(v ResultInfo) {
	o.ResultInfo = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetExchangeFeeInfoResponse) GetData() GetExchangeFeeInfoResponseData {
	if o == nil || o.Data == nil {
		var ret GetExchangeFeeInfoResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeFeeInfoResponse) GetDataOk() (*GetExchangeFeeInfoResponseData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetExchangeFeeInfoResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetExchangeFeeInfoResponseData and assigns it to the Data field.
func (o *GetExchangeFeeInfoResponse) SetData(v GetExchangeFeeInfoResponseData) {
	o.Data = &v
}

func (o GetExchangeFeeInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["resultInfo"] = o.ResultInfo
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetExchangeFeeInfoResponse struct {
	value *GetExchangeFeeInfoResponse
	isSet bool
}

func (v NullableGetExchangeFeeInfoResponse) Get() *GetExchangeFeeInfoResponse {
	return v.value
}

func (v *NullableGetExchangeFeeInfoResponse) Set(val *GetExchangeFeeInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetExchangeFeeInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetExchangeFeeInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetExchangeFeeInfoResponse(val *GetExchangeFeeInfoResponse) *NullableGetExchangeFeeInfoResponse {
	return &NullableGetExchangeFeeInfoResponse{value: val, isSet: true}
}

func (v NullableGetExchangeFeeInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetExchangeFeeInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
