/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// AmmSnapshot model.AmmSnapshot.description
type AmmSnapshot struct {
	// field.AmmSnapshot.poolName
	PoolName string `json:"poolName"`
	// field.AmmSnapshot.poolAddress
	PoolAddress string `json:"poolAddress"`
	// field.AmmSnapshot.poolTokenId
	PoolTokenId int32 `json:"poolTokenId"`
	// field.AmmSnapshot.PoolTokenAmount
	PoolTokenAmount string `json:"PoolTokenAmount"`
	// field.AmmSnapshot.tokenIds
	TokenIds []map[string]interface{} `json:"tokenIds"`
	// field.AmmSnapshot.tokenAmounts
	TokenAmounts []string `json:"tokenAmounts"`
	// field.AmmSnapshot.risky
	Risky bool `json:"risky"`
}

// NewAmmSnapshot instantiates a new AmmSnapshot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmmSnapshot(poolName string, poolAddress string, poolTokenId int32, poolTokenAmount string, tokenIds []map[string]interface{}, tokenAmounts []string, risky bool) *AmmSnapshot {
	this := AmmSnapshot{}
	this.PoolName = poolName
	this.PoolAddress = poolAddress
	this.PoolTokenId = poolTokenId
	this.PoolTokenAmount = poolTokenAmount
	this.TokenIds = tokenIds
	this.TokenAmounts = tokenAmounts
	this.Risky = risky
	return &this
}

// NewAmmSnapshotWithDefaults instantiates a new AmmSnapshot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmmSnapshotWithDefaults() *AmmSnapshot {
	this := AmmSnapshot{}
	return &this
}

// GetPoolName returns the PoolName field value
func (o *AmmSnapshot) GetPoolName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolName
}

// GetPoolNameOk returns a tuple with the PoolName field value
// and a boolean to check if the value has been set.
func (o *AmmSnapshot) GetPoolNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolName, true
}

// SetPoolName sets field value
func (o *AmmSnapshot) SetPoolName(v string) {
	o.PoolName = v
}

// GetPoolAddress returns the PoolAddress field value
func (o *AmmSnapshot) GetPoolAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolAddress
}

// GetPoolAddressOk returns a tuple with the PoolAddress field value
// and a boolean to check if the value has been set.
func (o *AmmSnapshot) GetPoolAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolAddress, true
}

// SetPoolAddress sets field value
func (o *AmmSnapshot) SetPoolAddress(v string) {
	o.PoolAddress = v
}

// GetPoolTokenId returns the PoolTokenId field value
func (o *AmmSnapshot) GetPoolTokenId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PoolTokenId
}

// GetPoolTokenIdOk returns a tuple with the PoolTokenId field value
// and a boolean to check if the value has been set.
func (o *AmmSnapshot) GetPoolTokenIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolTokenId, true
}

// SetPoolTokenId sets field value
func (o *AmmSnapshot) SetPoolTokenId(v int32) {
	o.PoolTokenId = v
}

// GetPoolTokenAmount returns the PoolTokenAmount field value
func (o *AmmSnapshot) GetPoolTokenAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolTokenAmount
}

// GetPoolTokenAmountOk returns a tuple with the PoolTokenAmount field value
// and a boolean to check if the value has been set.
func (o *AmmSnapshot) GetPoolTokenAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolTokenAmount, true
}

// SetPoolTokenAmount sets field value
func (o *AmmSnapshot) SetPoolTokenAmount(v string) {
	o.PoolTokenAmount = v
}

// GetTokenIds returns the TokenIds field value
func (o *AmmSnapshot) GetTokenIds() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.TokenIds
}

// GetTokenIdsOk returns a tuple with the TokenIds field value
// and a boolean to check if the value has been set.
func (o *AmmSnapshot) GetTokenIdsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.TokenIds, true
}

// SetTokenIds sets field value
func (o *AmmSnapshot) SetTokenIds(v []map[string]interface{}) {
	o.TokenIds = v
}

// GetTokenAmounts returns the TokenAmounts field value
func (o *AmmSnapshot) GetTokenAmounts() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TokenAmounts
}

// GetTokenAmountsOk returns a tuple with the TokenAmounts field value
// and a boolean to check if the value has been set.
func (o *AmmSnapshot) GetTokenAmountsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TokenAmounts, true
}

// SetTokenAmounts sets field value
func (o *AmmSnapshot) SetTokenAmounts(v []string) {
	o.TokenAmounts = v
}

// GetRisky returns the Risky field value
func (o *AmmSnapshot) GetRisky() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Risky
}

// GetRiskyOk returns a tuple with the Risky field value
// and a boolean to check if the value has been set.
func (o *AmmSnapshot) GetRiskyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Risky, true
}

// SetRisky sets field value
func (o *AmmSnapshot) SetRisky(v bool) {
	o.Risky = v
}

func (o AmmSnapshot) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["poolName"] = o.PoolName
	}
	if true {
		toSerialize["poolAddress"] = o.PoolAddress
	}
	if true {
		toSerialize["poolTokenId"] = o.PoolTokenId
	}
	if true {
		toSerialize["PoolTokenAmount"] = o.PoolTokenAmount
	}
	if true {
		toSerialize["tokenIds"] = o.TokenIds
	}
	if true {
		toSerialize["tokenAmounts"] = o.TokenAmounts
	}
	if true {
		toSerialize["risky"] = o.Risky
	}
	return json.Marshal(toSerialize)
}

type NullableAmmSnapshot struct {
	value *AmmSnapshot
	isSet bool
}

func (v NullableAmmSnapshot) Get() *AmmSnapshot {
	return v.value
}

func (v *NullableAmmSnapshot) Set(val *AmmSnapshot) {
	v.value = val
	v.isSet = true
}

func (v NullableAmmSnapshot) IsSet() bool {
	return v.isSet
}

func (v *NullableAmmSnapshot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmmSnapshot(val *AmmSnapshot) *NullableAmmSnapshot {
	return &NullableAmmSnapshot{value: val, isSet: true}
}

func (v NullableAmmSnapshot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmmSnapshot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
