/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// AmmMarketInfo struct for AmmMarketInfo
type AmmMarketInfo struct {
	// field.AmmMarketInfo.name
	Name string `json:"name"`
	// field.AmmMarketInfo.market
	Market string `json:"market"`
	// field.AmmMarketInfo.address
	Address string `json:"address"`
	// field.AmmMarketInfo.version
	Version string `json:"version"`
	// field.AmmMarketInfo.inPoolTokens
	InPoolTokens []map[string]interface{} `json:"inPoolTokens"`
	// field.AmmMarketInfo.poolTokenId
	PoolTokenId int32 `json:"poolTokenId"`
	// field.AmmMarketInfo.feeBips
	FeeBips int32 `json:"feeBips"`
	// field.AmmMarketInfo.pricePrecision
	PricePrecision int32 `json:"pricePrecision"`
	// field.AmmMarketInfo.amountPrecision
	AmountPrecision int32 `json:"amountPrecision"`
	// field.AmmMarketInfo.createdAt
	CreatedAt string `json:"createdAt"`
	// field.AmmMarketInfo.enabled
	Enabled bool `json:"enabled"`
	// field.AmmMarketInfo.status
	Status int32 `json:"status"`
}

// NewAmmMarketInfo instantiates a new AmmMarketInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmmMarketInfo(name string, market string, address string, version string, inPoolTokens []map[string]interface{}, poolTokenId int32, feeBips int32, pricePrecision int32, amountPrecision int32, createdAt string, enabled bool, status int32) *AmmMarketInfo {
	this := AmmMarketInfo{}
	this.Name = name
	this.Market = market
	this.Address = address
	this.Version = version
	this.InPoolTokens = inPoolTokens
	this.PoolTokenId = poolTokenId
	this.FeeBips = feeBips
	this.PricePrecision = pricePrecision
	this.AmountPrecision = amountPrecision
	this.CreatedAt = createdAt
	this.Enabled = enabled
	this.Status = status
	return &this
}

// NewAmmMarketInfoWithDefaults instantiates a new AmmMarketInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmmMarketInfoWithDefaults() *AmmMarketInfo {
	this := AmmMarketInfo{}
	return &this
}

// GetName returns the Name field value
func (o *AmmMarketInfo) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AmmMarketInfo) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AmmMarketInfo) SetName(v string) {
	o.Name = v
}

// GetMarket returns the Market field value
func (o *AmmMarketInfo) GetMarket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Market
}

// GetMarketOk returns a tuple with the Market field value
// and a boolean to check if the value has been set.
func (o *AmmMarketInfo) GetMarketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Market, true
}

// SetMarket sets field value
func (o *AmmMarketInfo) SetMarket(v string) {
	o.Market = v
}

// GetAddress returns the Address field value
func (o *AmmMarketInfo) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *AmmMarketInfo) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *AmmMarketInfo) SetAddress(v string) {
	o.Address = v
}

// GetVersion returns the Version field value
func (o *AmmMarketInfo) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *AmmMarketInfo) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *AmmMarketInfo) SetVersion(v string) {
	o.Version = v
}

// GetInPoolTokens returns the InPoolTokens field value
func (o *AmmMarketInfo) GetInPoolTokens() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.InPoolTokens
}

// GetInPoolTokensOk returns a tuple with the InPoolTokens field value
// and a boolean to check if the value has been set.
func (o *AmmMarketInfo) GetInPoolTokensOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.InPoolTokens, true
}

// SetInPoolTokens sets field value
func (o *AmmMarketInfo) SetInPoolTokens(v []map[string]interface{}) {
	o.InPoolTokens = v
}

// GetPoolTokenId returns the PoolTokenId field value
func (o *AmmMarketInfo) GetPoolTokenId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PoolTokenId
}

// GetPoolTokenIdOk returns a tuple with the PoolTokenId field value
// and a boolean to check if the value has been set.
func (o *AmmMarketInfo) GetPoolTokenIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolTokenId, true
}

// SetPoolTokenId sets field value
func (o *AmmMarketInfo) SetPoolTokenId(v int32) {
	o.PoolTokenId = v
}

// GetFeeBips returns the FeeBips field value
func (o *AmmMarketInfo) GetFeeBips() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FeeBips
}

// GetFeeBipsOk returns a tuple with the FeeBips field value
// and a boolean to check if the value has been set.
func (o *AmmMarketInfo) GetFeeBipsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeBips, true
}

// SetFeeBips sets field value
func (o *AmmMarketInfo) SetFeeBips(v int32) {
	o.FeeBips = v
}

// GetPricePrecision returns the PricePrecision field value
func (o *AmmMarketInfo) GetPricePrecision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PricePrecision
}

// GetPricePrecisionOk returns a tuple with the PricePrecision field value
// and a boolean to check if the value has been set.
func (o *AmmMarketInfo) GetPricePrecisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PricePrecision, true
}

// SetPricePrecision sets field value
func (o *AmmMarketInfo) SetPricePrecision(v int32) {
	o.PricePrecision = v
}

// GetAmountPrecision returns the AmountPrecision field value
func (o *AmmMarketInfo) GetAmountPrecision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AmountPrecision
}

// GetAmountPrecisionOk returns a tuple with the AmountPrecision field value
// and a boolean to check if the value has been set.
func (o *AmmMarketInfo) GetAmountPrecisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountPrecision, true
}

// SetAmountPrecision sets field value
func (o *AmmMarketInfo) SetAmountPrecision(v int32) {
	o.AmountPrecision = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AmmMarketInfo) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AmmMarketInfo) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AmmMarketInfo) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetEnabled returns the Enabled field value
func (o *AmmMarketInfo) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *AmmMarketInfo) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *AmmMarketInfo) SetEnabled(v bool) {
	o.Enabled = v
}

// GetStatus returns the Status field value
func (o *AmmMarketInfo) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AmmMarketInfo) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AmmMarketInfo) SetStatus(v int32) {
	o.Status = v
}

func (o AmmMarketInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["market"] = o.Market
	}
	if true {
		toSerialize["address"] = o.Address
	}
	if true {
		toSerialize["version"] = o.Version
	}
	if true {
		toSerialize["inPoolTokens"] = o.InPoolTokens
	}
	if true {
		toSerialize["poolTokenId"] = o.PoolTokenId
	}
	if true {
		toSerialize["feeBips"] = o.FeeBips
	}
	if true {
		toSerialize["pricePrecision"] = o.PricePrecision
	}
	if true {
		toSerialize["amountPrecision"] = o.AmountPrecision
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["enabled"] = o.Enabled
	}
	if true {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableAmmMarketInfo struct {
	value *AmmMarketInfo
	isSet bool
}

func (v NullableAmmMarketInfo) Get() *AmmMarketInfo {
	return v.value
}

func (v *NullableAmmMarketInfo) Set(val *AmmMarketInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAmmMarketInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAmmMarketInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmmMarketInfo(val *AmmMarketInfo) *NullableAmmMarketInfo {
	return &NullableAmmMarketInfo{value: val, isSet: true}
}

func (v NullableAmmMarketInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmmMarketInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
