/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// GetEthNonceV2Response Query the result returned by Ethereum address nonce
type GetEthNonceV2Response struct {
	ResultInfo ResultInfo `json:"resultInfo"`
	// The result of nonce
	Data *int64 `json:"data,omitempty"`
}

// NewGetEthNonceV2Response instantiates a new GetEthNonceV2Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEthNonceV2Response(resultInfo ResultInfo) *GetEthNonceV2Response {
	this := GetEthNonceV2Response{}
	this.ResultInfo = resultInfo
	return &this
}

// NewGetEthNonceV2ResponseWithDefaults instantiates a new GetEthNonceV2Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEthNonceV2ResponseWithDefaults() *GetEthNonceV2Response {
	this := GetEthNonceV2Response{}
	return &this
}

// GetResultInfo returns the ResultInfo field value
func (o *GetEthNonceV2Response) GetResultInfo() ResultInfo {
	if o == nil {
		var ret ResultInfo
		return ret
	}

	return o.ResultInfo
}

// GetResultInfoOk returns a tuple with the ResultInfo field value
// and a boolean to check if the value has been set.
func (o *GetEthNonceV2Response) GetResultInfoOk() (*ResultInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultInfo, true
}

// SetResultInfo sets field value
func (o *GetEthNonceV2Response) SetResultInfo(v ResultInfo) {
	o.ResultInfo = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetEthNonceV2Response) GetData() int64 {
	if o == nil || o.Data == nil {
		var ret int64
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthNonceV2Response) GetDataOk() (*int64, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetEthNonceV2Response) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given int64 and assigns it to the Data field.
func (o *GetEthNonceV2Response) SetData(v int64) {
	o.Data = &v
}

func (o GetEthNonceV2Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["resultInfo"] = o.ResultInfo
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetEthNonceV2Response struct {
	value *GetEthNonceV2Response
	isSet bool
}

func (v NullableGetEthNonceV2Response) Get() *GetEthNonceV2Response {
	return v.value
}

func (v *NullableGetEthNonceV2Response) Set(val *GetEthNonceV2Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEthNonceV2Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEthNonceV2Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEthNonceV2Response(val *GetEthNonceV2Response) *NullableGetEthNonceV2Response {
	return &NullableGetEthNonceV2Response{value: val, isSet: true}
}

func (v NullableGetEthNonceV2Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEthNonceV2Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
