/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// GetUserTradesResponseV2 Response body
type GetUserTradesResponseV2 struct {
	ResultInfo ResultInfo `json:"resultInfo"`
	Data       *TradeList `json:"data,omitempty"`
}

// NewGetUserTradesResponseV2 instantiates a new GetUserTradesResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserTradesResponseV2(resultInfo ResultInfo) *GetUserTradesResponseV2 {
	this := GetUserTradesResponseV2{}
	this.ResultInfo = resultInfo
	return &this
}

// NewGetUserTradesResponseV2WithDefaults instantiates a new GetUserTradesResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserTradesResponseV2WithDefaults() *GetUserTradesResponseV2 {
	this := GetUserTradesResponseV2{}
	return &this
}

// GetResultInfo returns the ResultInfo field value
func (o *GetUserTradesResponseV2) GetResultInfo() ResultInfo {
	if o == nil {
		var ret ResultInfo
		return ret
	}

	return o.ResultInfo
}

// GetResultInfoOk returns a tuple with the ResultInfo field value
// and a boolean to check if the value has been set.
func (o *GetUserTradesResponseV2) GetResultInfoOk() (*ResultInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultInfo, true
}

// SetResultInfo sets field value
func (o *GetUserTradesResponseV2) SetResultInfo(v ResultInfo) {
	o.ResultInfo = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetUserTradesResponseV2) GetData() TradeList {
	if o == nil || o.Data == nil {
		var ret TradeList
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserTradesResponseV2) GetDataOk() (*TradeList, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetUserTradesResponseV2) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given TradeList and assigns it to the Data field.
func (o *GetUserTradesResponseV2) SetData(v TradeList) {
	o.Data = &v
}

func (o GetUserTradesResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["resultInfo"] = o.ResultInfo
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetUserTradesResponseV2 struct {
	value *GetUserTradesResponseV2
	isSet bool
}

func (v NullableGetUserTradesResponseV2) Get() *GetUserTradesResponseV2 {
	return v.value
}

func (v *NullableGetUserTradesResponseV2) Set(val *GetUserTradesResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserTradesResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserTradesResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserTradesResponseV2(val *GetUserTradesResponseV2) *NullableGetUserTradesResponseV2 {
	return &NullableGetUserTradesResponseV2{value: val, isSet: true}
}

func (v NullableGetUserTradesResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserTradesResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
