/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// GetUserCreateResponseV2 Response body
type GetUserCreateResponseV2 struct {
	ResultInfo ResultInfo          `json:"resultInfo"`
	Data       *UserCreateDataList `json:"data,omitempty"`
}

// NewGetUserCreateResponseV2 instantiates a new GetUserCreateResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserCreateResponseV2(resultInfo ResultInfo) *GetUserCreateResponseV2 {
	this := GetUserCreateResponseV2{}
	this.ResultInfo = resultInfo
	return &this
}

// NewGetUserCreateResponseV2WithDefaults instantiates a new GetUserCreateResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserCreateResponseV2WithDefaults() *GetUserCreateResponseV2 {
	this := GetUserCreateResponseV2{}
	return &this
}

// GetResultInfo returns the ResultInfo field value
func (o *GetUserCreateResponseV2) GetResultInfo() ResultInfo {
	if o == nil {
		var ret ResultInfo
		return ret
	}

	return o.ResultInfo
}

// GetResultInfoOk returns a tuple with the ResultInfo field value
// and a boolean to check if the value has been set.
func (o *GetUserCreateResponseV2) GetResultInfoOk() (*ResultInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultInfo, true
}

// SetResultInfo sets field value
func (o *GetUserCreateResponseV2) SetResultInfo(v ResultInfo) {
	o.ResultInfo = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetUserCreateResponseV2) GetData() UserCreateDataList {
	if o == nil || o.Data == nil {
		var ret UserCreateDataList
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserCreateResponseV2) GetDataOk() (*UserCreateDataList, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetUserCreateResponseV2) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given UserCreateDataList and assigns it to the Data field.
func (o *GetUserCreateResponseV2) SetData(v UserCreateDataList) {
	o.Data = &v
}

func (o GetUserCreateResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["resultInfo"] = o.ResultInfo
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetUserCreateResponseV2 struct {
	value *GetUserCreateResponseV2
	isSet bool
}

func (v NullableGetUserCreateResponseV2) Get() *GetUserCreateResponseV2 {
	return v.value
}

func (v *NullableGetUserCreateResponseV2) Set(val *GetUserCreateResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserCreateResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserCreateResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserCreateResponseV2(val *GetUserCreateResponseV2) *NullableGetUserCreateResponseV2 {
	return &NullableGetUserCreateResponseV2{value: val, isSet: true}
}

func (v NullableGetUserCreateResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserCreateResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
