/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// AmmTransferDataV3 AMM transfer info data
type AmmTransferDataV3 struct {
	// AMM transfer token id
	TokenId int32 `json:"tokenId"`
	// AMM transfer token amount
	Amount string `json:"amount"`
	// Actual AMM transfer token amount due to precision processing
	ActualAmount string `json:"actualAmount"`
	// Actual AMM transfer fee amount
	FeeAmount string `json:"feeAmount"`
}

// NewAmmTransferDataV3 instantiates a new AmmTransferDataV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmmTransferDataV3(tokenId int32, amount string, actualAmount string, feeAmount string) *AmmTransferDataV3 {
	this := AmmTransferDataV3{}
	this.TokenId = tokenId
	this.Amount = amount
	this.ActualAmount = actualAmount
	this.FeeAmount = feeAmount
	return &this
}

// NewAmmTransferDataV3WithDefaults instantiates a new AmmTransferDataV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmmTransferDataV3WithDefaults() *AmmTransferDataV3 {
	this := AmmTransferDataV3{}
	return &this
}

// GetTokenId returns the TokenId field value
func (o *AmmTransferDataV3) GetTokenId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *AmmTransferDataV3) GetTokenIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *AmmTransferDataV3) SetTokenId(v int32) {
	o.TokenId = v
}

// GetAmount returns the Amount field value
func (o *AmmTransferDataV3) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *AmmTransferDataV3) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *AmmTransferDataV3) SetAmount(v string) {
	o.Amount = v
}

// GetActualAmount returns the ActualAmount field value
func (o *AmmTransferDataV3) GetActualAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActualAmount
}

// GetActualAmountOk returns a tuple with the ActualAmount field value
// and a boolean to check if the value has been set.
func (o *AmmTransferDataV3) GetActualAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActualAmount, true
}

// SetActualAmount sets field value
func (o *AmmTransferDataV3) SetActualAmount(v string) {
	o.ActualAmount = v
}

// GetFeeAmount returns the FeeAmount field value
func (o *AmmTransferDataV3) GetFeeAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeeAmount
}

// GetFeeAmountOk returns a tuple with the FeeAmount field value
// and a boolean to check if the value has been set.
func (o *AmmTransferDataV3) GetFeeAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeAmount, true
}

// SetFeeAmount sets field value
func (o *AmmTransferDataV3) SetFeeAmount(v string) {
	o.FeeAmount = v
}

func (o AmmTransferDataV3) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tokenId"] = o.TokenId
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["actualAmount"] = o.ActualAmount
	}
	if true {
		toSerialize["feeAmount"] = o.FeeAmount
	}
	return json.Marshal(toSerialize)
}

type NullableAmmTransferDataV3 struct {
	value *AmmTransferDataV3
	isSet bool
}

func (v NullableAmmTransferDataV3) Get() *AmmTransferDataV3 {
	return v.value
}

func (v *NullableAmmTransferDataV3) Set(val *AmmTransferDataV3) {
	v.value = val
	v.isSet = true
}

func (v NullableAmmTransferDataV3) IsSet() bool {
	return v.isSet
}

func (v *NullableAmmTransferDataV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmmTransferDataV3(val *AmmTransferDataV3) *NullableAmmTransferDataV3 {
	return &NullableAmmTransferDataV3{value: val, isSet: true}
}

func (v NullableAmmTransferDataV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmmTransferDataV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
