/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// GetAccountResponseV2 model.getAccountResponse
type GetAccountResponseV2 struct {
	ResultInfo ResultInfo `json:"resultInfo"`
	Data       DexAccount `json:"data"`
}

// NewGetAccountResponseV2 instantiates a new GetAccountResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountResponseV2(resultInfo ResultInfo, data DexAccount) *GetAccountResponseV2 {
	this := GetAccountResponseV2{}
	this.ResultInfo = resultInfo
	this.Data = data
	return &this
}

// NewGetAccountResponseV2WithDefaults instantiates a new GetAccountResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountResponseV2WithDefaults() *GetAccountResponseV2 {
	this := GetAccountResponseV2{}
	return &this
}

// GetResultInfo returns the ResultInfo field value
func (o *GetAccountResponseV2) GetResultInfo() ResultInfo {
	if o == nil {
		var ret ResultInfo
		return ret
	}

	return o.ResultInfo
}

// GetResultInfoOk returns a tuple with the ResultInfo field value
// and a boolean to check if the value has been set.
func (o *GetAccountResponseV2) GetResultInfoOk() (*ResultInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultInfo, true
}

// SetResultInfo sets field value
func (o *GetAccountResponseV2) SetResultInfo(v ResultInfo) {
	o.ResultInfo = v
}

// GetData returns the Data field value
func (o *GetAccountResponseV2) GetData() DexAccount {
	if o == nil {
		var ret DexAccount
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetAccountResponseV2) GetDataOk() (*DexAccount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetAccountResponseV2) SetData(v DexAccount) {
	o.Data = v
}

func (o GetAccountResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["resultInfo"] = o.ResultInfo
	}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetAccountResponseV2 struct {
	value *GetAccountResponseV2
	isSet bool
}

func (v NullableGetAccountResponseV2) Get() *GetAccountResponseV2 {
	return v.value
}

func (v *NullableGetAccountResponseV2) Set(val *GetAccountResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountResponseV2(val *GetAccountResponseV2) *NullableGetAccountResponseV2 {
	return &NullableGetAccountResponseV2{value: val, isSet: true}
}

func (v NullableGetAccountResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
