/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// AmmTransactionDataList struct for AmmTransactionDataList
type AmmTransactionDataList struct {
	TotalNum     int64                `json:"totalNum"`
	Transactions []AmmTransactionData `json:"transactions"`
}

// NewAmmTransactionDataList instantiates a new AmmTransactionDataList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmmTransactionDataList(totalNum int64, transactions []AmmTransactionData) *AmmTransactionDataList {
	this := AmmTransactionDataList{}
	this.TotalNum = totalNum
	this.Transactions = transactions
	return &this
}

// NewAmmTransactionDataListWithDefaults instantiates a new AmmTransactionDataList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmmTransactionDataListWithDefaults() *AmmTransactionDataList {
	this := AmmTransactionDataList{}
	return &this
}

// GetTotalNum returns the TotalNum field value
func (o *AmmTransactionDataList) GetTotalNum() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalNum
}

// GetTotalNumOk returns a tuple with the TotalNum field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionDataList) GetTotalNumOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalNum, true
}

// SetTotalNum sets field value
func (o *AmmTransactionDataList) SetTotalNum(v int64) {
	o.TotalNum = v
}

// GetTransactions returns the Transactions field value
func (o *AmmTransactionDataList) GetTransactions() []AmmTransactionData {
	if o == nil {
		var ret []AmmTransactionData
		return ret
	}

	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value
// and a boolean to check if the value has been set.
func (o *AmmTransactionDataList) GetTransactionsOk() ([]AmmTransactionData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transactions, true
}

// SetTransactions sets field value
func (o *AmmTransactionDataList) SetTransactions(v []AmmTransactionData) {
	o.Transactions = v
}

func (o AmmTransactionDataList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["totalNum"] = o.TotalNum
	}
	if true {
		toSerialize["transactions"] = o.Transactions
	}
	return json.Marshal(toSerialize)
}

type NullableAmmTransactionDataList struct {
	value *AmmTransactionDataList
	isSet bool
}

func (v NullableAmmTransactionDataList) Get() *AmmTransactionDataList {
	return v.value
}

func (v *NullableAmmTransactionDataList) Set(val *AmmTransactionDataList) {
	v.value = val
	v.isSet = true
}

func (v NullableAmmTransactionDataList) IsSet() bool {
	return v.isSet
}

func (v *NullableAmmTransactionDataList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmmTransactionDataList(val *AmmTransactionDataList) *NullableAmmTransactionDataList {
	return &NullableAmmTransactionDataList{value: val, isSet: true}
}

func (v NullableAmmTransactionDataList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmmTransactionDataList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
