/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// GetLuckyTokenAgentsResponse struct for GetLuckyTokenAgentsResponse
type GetLuckyTokenAgentsResponse struct {
	ResultInfo ResultInfo `json:"resultInfo"`
	// model.GetAmmUserPoolsStatsResponse
	Data []LuckyTokenAgent `json:"data"`
}

// NewGetLuckyTokenAgentsResponse instantiates a new GetLuckyTokenAgentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLuckyTokenAgentsResponse(resultInfo ResultInfo, data []LuckyTokenAgent) *GetLuckyTokenAgentsResponse {
	this := GetLuckyTokenAgentsResponse{}
	this.ResultInfo = resultInfo
	this.Data = data
	return &this
}

// NewGetLuckyTokenAgentsResponseWithDefaults instantiates a new GetLuckyTokenAgentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLuckyTokenAgentsResponseWithDefaults() *GetLuckyTokenAgentsResponse {
	this := GetLuckyTokenAgentsResponse{}
	return &this
}

// GetResultInfo returns the ResultInfo field value
func (o *GetLuckyTokenAgentsResponse) GetResultInfo() ResultInfo {
	if o == nil {
		var ret ResultInfo
		return ret
	}

	return o.ResultInfo
}

// GetResultInfoOk returns a tuple with the ResultInfo field value
// and a boolean to check if the value has been set.
func (o *GetLuckyTokenAgentsResponse) GetResultInfoOk() (*ResultInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultInfo, true
}

// SetResultInfo sets field value
func (o *GetLuckyTokenAgentsResponse) SetResultInfo(v ResultInfo) {
	o.ResultInfo = v
}

// GetData returns the Data field value
func (o *GetLuckyTokenAgentsResponse) GetData() []LuckyTokenAgent {
	if o == nil {
		var ret []LuckyTokenAgent
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetLuckyTokenAgentsResponse) GetDataOk() ([]LuckyTokenAgent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetLuckyTokenAgentsResponse) SetData(v []LuckyTokenAgent) {
	o.Data = v
}

func (o GetLuckyTokenAgentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["resultInfo"] = o.ResultInfo
	}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetLuckyTokenAgentsResponse struct {
	value *GetLuckyTokenAgentsResponse
	isSet bool
}

func (v NullableGetLuckyTokenAgentsResponse) Get() *GetLuckyTokenAgentsResponse {
	return v.value
}

func (v *NullableGetLuckyTokenAgentsResponse) Set(val *GetLuckyTokenAgentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLuckyTokenAgentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLuckyTokenAgentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLuckyTokenAgentsResponse(val *GetLuckyTokenAgentsResponse) *NullableGetLuckyTokenAgentsResponse {
	return &NullableGetLuckyTokenAgentsResponse{value: val, isSet: true}
}

func (v NullableGetLuckyTokenAgentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLuckyTokenAgentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
