/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// MarketTradesV3 model.marketTrades
type MarketTradesV3 struct {
	// The total number of trades in query result
	TotalNum int64 `json:"totalNum"`
	// List of trades records, each trade record in the order of the array is the trade time, record id, buying and selling direction, volume, price, market, fees, blockId and indexInBlock
	Trades [][]string `json:"trades"`
}

// NewMarketTradesV3 instantiates a new MarketTradesV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketTradesV3(totalNum int64, trades [][]string) *MarketTradesV3 {
	this := MarketTradesV3{}
	this.TotalNum = totalNum
	this.Trades = trades
	return &this
}

// NewMarketTradesV3WithDefaults instantiates a new MarketTradesV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketTradesV3WithDefaults() *MarketTradesV3 {
	this := MarketTradesV3{}
	return &this
}

// GetTotalNum returns the TotalNum field value
func (o *MarketTradesV3) GetTotalNum() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalNum
}

// GetTotalNumOk returns a tuple with the TotalNum field value
// and a boolean to check if the value has been set.
func (o *MarketTradesV3) GetTotalNumOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalNum, true
}

// SetTotalNum sets field value
func (o *MarketTradesV3) SetTotalNum(v int64) {
	o.TotalNum = v
}

// GetTrades returns the Trades field value
func (o *MarketTradesV3) GetTrades() [][]string {
	if o == nil {
		var ret [][]string
		return ret
	}

	return o.Trades
}

// GetTradesOk returns a tuple with the Trades field value
// and a boolean to check if the value has been set.
func (o *MarketTradesV3) GetTradesOk() ([][]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Trades, true
}

// SetTrades sets field value
func (o *MarketTradesV3) SetTrades(v [][]string) {
	o.Trades = v
}

func (o MarketTradesV3) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["totalNum"] = o.TotalNum
	}
	if true {
		toSerialize["trades"] = o.Trades
	}
	return json.Marshal(toSerialize)
}

type NullableMarketTradesV3 struct {
	value *MarketTradesV3
	isSet bool
}

func (v NullableMarketTradesV3) Get() *MarketTradesV3 {
	return v.value
}

func (v *NullableMarketTradesV3) Set(val *MarketTradesV3) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketTradesV3) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketTradesV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketTradesV3(val *MarketTradesV3) *NullableMarketTradesV3 {
	return &NullableMarketTradesV3{value: val, isSet: true}
}

func (v NullableMarketTradesV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketTradesV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
