/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// AmmPoolStatistics model.AmmPoolStatistics
type AmmPoolStatistics struct {
	// field.AmmPoolStatistics.market
	Market string `json:"market"`
	// field.AmmPoolStatistics.liquidity
	Liquidity []string `json:"liquidity"`
	// field.AmmPoolStatistics.lpLiquidity
	LpLiquidity string `json:"lpLiquidity"`
	// field.AmmPoolStatistics.liquidityUSD
	LiquidityUSD string `json:"liquidityUSD"`
	// field.AmmPoolStatistics.ohlc
	Ohlc []string `json:"ohlc"`
	// field.AmmPoolStatistics.volume
	Volume []string `json:"volume"`
	// field.AmmPoolStatistics.fees
	Fees []string `json:"fees"`
	// field.AmmPoolStatistics.apyBips
	ApyBips string `json:"apyBips"`
	// field.AmmPoolStatistics.isRecommended
	IsRecommended bool `json:"isRecommended"`
	// field.AmmPoolStatistics.rewards
	Rewards []TokenVolumeV3 `json:"rewards"`
}

// NewAmmPoolStatistics instantiates a new AmmPoolStatistics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmmPoolStatistics(market string, liquidity []string, lpLiquidity string, liquidityUSD string, ohlc []string, volume []string, fees []string, apyBips string, isRecommended bool, rewards []TokenVolumeV3) *AmmPoolStatistics {
	this := AmmPoolStatistics{}
	this.Market = market
	this.Liquidity = liquidity
	this.LpLiquidity = lpLiquidity
	this.LiquidityUSD = liquidityUSD
	this.Ohlc = ohlc
	this.Volume = volume
	this.Fees = fees
	this.ApyBips = apyBips
	this.IsRecommended = isRecommended
	this.Rewards = rewards
	return &this
}

// NewAmmPoolStatisticsWithDefaults instantiates a new AmmPoolStatistics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmmPoolStatisticsWithDefaults() *AmmPoolStatistics {
	this := AmmPoolStatistics{}
	return &this
}

// GetMarket returns the Market field value
func (o *AmmPoolStatistics) GetMarket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Market
}

// GetMarketOk returns a tuple with the Market field value
// and a boolean to check if the value has been set.
func (o *AmmPoolStatistics) GetMarketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Market, true
}

// SetMarket sets field value
func (o *AmmPoolStatistics) SetMarket(v string) {
	o.Market = v
}

// GetLiquidity returns the Liquidity field value
func (o *AmmPoolStatistics) GetLiquidity() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Liquidity
}

// GetLiquidityOk returns a tuple with the Liquidity field value
// and a boolean to check if the value has been set.
func (o *AmmPoolStatistics) GetLiquidityOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Liquidity, true
}

// SetLiquidity sets field value
func (o *AmmPoolStatistics) SetLiquidity(v []string) {
	o.Liquidity = v
}

// GetLpLiquidity returns the LpLiquidity field value
func (o *AmmPoolStatistics) GetLpLiquidity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LpLiquidity
}

// GetLpLiquidityOk returns a tuple with the LpLiquidity field value
// and a boolean to check if the value has been set.
func (o *AmmPoolStatistics) GetLpLiquidityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LpLiquidity, true
}

// SetLpLiquidity sets field value
func (o *AmmPoolStatistics) SetLpLiquidity(v string) {
	o.LpLiquidity = v
}

// GetLiquidityUSD returns the LiquidityUSD field value
func (o *AmmPoolStatistics) GetLiquidityUSD() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LiquidityUSD
}

// GetLiquidityUSDOk returns a tuple with the LiquidityUSD field value
// and a boolean to check if the value has been set.
func (o *AmmPoolStatistics) GetLiquidityUSDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LiquidityUSD, true
}

// SetLiquidityUSD sets field value
func (o *AmmPoolStatistics) SetLiquidityUSD(v string) {
	o.LiquidityUSD = v
}

// GetOhlc returns the Ohlc field value
func (o *AmmPoolStatistics) GetOhlc() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ohlc
}

// GetOhlcOk returns a tuple with the Ohlc field value
// and a boolean to check if the value has been set.
func (o *AmmPoolStatistics) GetOhlcOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ohlc, true
}

// SetOhlc sets field value
func (o *AmmPoolStatistics) SetOhlc(v []string) {
	o.Ohlc = v
}

// GetVolume returns the Volume field value
func (o *AmmPoolStatistics) GetVolume() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value
// and a boolean to check if the value has been set.
func (o *AmmPoolStatistics) GetVolumeOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Volume, true
}

// SetVolume sets field value
func (o *AmmPoolStatistics) SetVolume(v []string) {
	o.Volume = v
}

// GetFees returns the Fees field value
func (o *AmmPoolStatistics) GetFees() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Fees
}

// GetFeesOk returns a tuple with the Fees field value
// and a boolean to check if the value has been set.
func (o *AmmPoolStatistics) GetFeesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fees, true
}

// SetFees sets field value
func (o *AmmPoolStatistics) SetFees(v []string) {
	o.Fees = v
}

// GetApyBips returns the ApyBips field value
func (o *AmmPoolStatistics) GetApyBips() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApyBips
}

// GetApyBipsOk returns a tuple with the ApyBips field value
// and a boolean to check if the value has been set.
func (o *AmmPoolStatistics) GetApyBipsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApyBips, true
}

// SetApyBips sets field value
func (o *AmmPoolStatistics) SetApyBips(v string) {
	o.ApyBips = v
}

// GetIsRecommended returns the IsRecommended field value
func (o *AmmPoolStatistics) GetIsRecommended() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsRecommended
}

// GetIsRecommendedOk returns a tuple with the IsRecommended field value
// and a boolean to check if the value has been set.
func (o *AmmPoolStatistics) GetIsRecommendedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsRecommended, true
}

// SetIsRecommended sets field value
func (o *AmmPoolStatistics) SetIsRecommended(v bool) {
	o.IsRecommended = v
}

// GetRewards returns the Rewards field value
func (o *AmmPoolStatistics) GetRewards() []TokenVolumeV3 {
	if o == nil {
		var ret []TokenVolumeV3
		return ret
	}

	return o.Rewards
}

// GetRewardsOk returns a tuple with the Rewards field value
// and a boolean to check if the value has been set.
func (o *AmmPoolStatistics) GetRewardsOk() ([]TokenVolumeV3, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rewards, true
}

// SetRewards sets field value
func (o *AmmPoolStatistics) SetRewards(v []TokenVolumeV3) {
	o.Rewards = v
}

func (o AmmPoolStatistics) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["market"] = o.Market
	}
	if true {
		toSerialize["liquidity"] = o.Liquidity
	}
	if true {
		toSerialize["lpLiquidity"] = o.LpLiquidity
	}
	if true {
		toSerialize["liquidityUSD"] = o.LiquidityUSD
	}
	if true {
		toSerialize["ohlc"] = o.Ohlc
	}
	if true {
		toSerialize["volume"] = o.Volume
	}
	if true {
		toSerialize["fees"] = o.Fees
	}
	if true {
		toSerialize["apyBips"] = o.ApyBips
	}
	if true {
		toSerialize["isRecommended"] = o.IsRecommended
	}
	if true {
		toSerialize["rewards"] = o.Rewards
	}
	return json.Marshal(toSerialize)
}

type NullableAmmPoolStatistics struct {
	value *AmmPoolStatistics
	isSet bool
}

func (v NullableAmmPoolStatistics) Get() *AmmPoolStatistics {
	return v.value
}

func (v *NullableAmmPoolStatistics) Set(val *AmmPoolStatistics) {
	v.value = val
	v.isSet = true
}

func (v NullableAmmPoolStatistics) IsSet() bool {
	return v.isSet
}

func (v *NullableAmmPoolStatistics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmmPoolStatistics(val *AmmPoolStatistics) *NullableAmmPoolStatistics {
	return &NullableAmmPoolStatistics{value: val, isSet: true}
}

func (v NullableAmmPoolStatistics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmmPoolStatistics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
