/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// GetEthBalancesV2Response The query result of Ethereum address ETH balance
type GetEthBalancesV2Response struct {
	ResultInfo ResultInfo `json:"resultInfo"`
	// Balance in wei
	Data *string `json:"data,omitempty"`
}

// NewGetEthBalancesV2Response instantiates a new GetEthBalancesV2Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEthBalancesV2Response(resultInfo ResultInfo) *GetEthBalancesV2Response {
	this := GetEthBalancesV2Response{}
	this.ResultInfo = resultInfo
	return &this
}

// NewGetEthBalancesV2ResponseWithDefaults instantiates a new GetEthBalancesV2Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEthBalancesV2ResponseWithDefaults() *GetEthBalancesV2Response {
	this := GetEthBalancesV2Response{}
	return &this
}

// GetResultInfo returns the ResultInfo field value
func (o *GetEthBalancesV2Response) GetResultInfo() ResultInfo {
	if o == nil {
		var ret ResultInfo
		return ret
	}

	return o.ResultInfo
}

// GetResultInfoOk returns a tuple with the ResultInfo field value
// and a boolean to check if the value has been set.
func (o *GetEthBalancesV2Response) GetResultInfoOk() (*ResultInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultInfo, true
}

// SetResultInfo sets field value
func (o *GetEthBalancesV2Response) SetResultInfo(v ResultInfo) {
	o.ResultInfo = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetEthBalancesV2Response) GetData() string {
	if o == nil || o.Data == nil {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEthBalancesV2Response) GetDataOk() (*string, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetEthBalancesV2Response) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *GetEthBalancesV2Response) SetData(v string) {
	o.Data = &v
}

func (o GetEthBalancesV2Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["resultInfo"] = o.ResultInfo
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetEthBalancesV2Response struct {
	value *GetEthBalancesV2Response
	isSet bool
}

func (v NullableGetEthBalancesV2Response) Get() *GetEthBalancesV2Response {
	return v.value
}

func (v *NullableGetEthBalancesV2Response) Set(val *GetEthBalancesV2Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEthBalancesV2Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEthBalancesV2Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEthBalancesV2Response(val *GetEthBalancesV2Response) *NullableGetEthBalancesV2Response {
	return &NullableGetEthBalancesV2Response{value: val, isSet: true}
}

func (v NullableGetEthBalancesV2Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEthBalancesV2Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
