/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// GetUserDepositResponseV2 Response body
type GetUserDepositResponseV2 struct {
	ResultInfo ResultInfo       `json:"resultInfo"`
	Data       *DepositDataList `json:"data,omitempty"`
}

// NewGetUserDepositResponseV2 instantiates a new GetUserDepositResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserDepositResponseV2(resultInfo ResultInfo) *GetUserDepositResponseV2 {
	this := GetUserDepositResponseV2{}
	this.ResultInfo = resultInfo
	return &this
}

// NewGetUserDepositResponseV2WithDefaults instantiates a new GetUserDepositResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserDepositResponseV2WithDefaults() *GetUserDepositResponseV2 {
	this := GetUserDepositResponseV2{}
	return &this
}

// GetResultInfo returns the ResultInfo field value
func (o *GetUserDepositResponseV2) GetResultInfo() ResultInfo {
	if o == nil {
		var ret ResultInfo
		return ret
	}

	return o.ResultInfo
}

// GetResultInfoOk returns a tuple with the ResultInfo field value
// and a boolean to check if the value has been set.
func (o *GetUserDepositResponseV2) GetResultInfoOk() (*ResultInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultInfo, true
}

// SetResultInfo sets field value
func (o *GetUserDepositResponseV2) SetResultInfo(v ResultInfo) {
	o.ResultInfo = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetUserDepositResponseV2) GetData() DepositDataList {
	if o == nil || o.Data == nil {
		var ret DepositDataList
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserDepositResponseV2) GetDataOk() (*DepositDataList, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetUserDepositResponseV2) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given DepositDataList and assigns it to the Data field.
func (o *GetUserDepositResponseV2) SetData(v DepositDataList) {
	o.Data = &v
}

func (o GetUserDepositResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["resultInfo"] = o.ResultInfo
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetUserDepositResponseV2 struct {
	value *GetUserDepositResponseV2
	isSet bool
}

func (v NullableGetUserDepositResponseV2) Get() *GetUserDepositResponseV2 {
	return v.value
}

func (v *NullableGetUserDepositResponseV2) Set(val *GetUserDepositResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserDepositResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserDepositResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserDepositResponseV2(val *GetUserDepositResponseV2) *NullableGetUserDepositResponseV2 {
	return &NullableGetUserDepositResponseV2{value: val, isSet: true}
}

func (v NullableGetUserDepositResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserDepositResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
