/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// GetAmmPoolsStatsResponse struct for GetAmmPoolsStatsResponse
type GetAmmPoolsStatsResponse struct {
	ResultInfo ResultInfo `json:"resultInfo"`
	// model.AmmPoolStatistics
	Data []AmmPoolStatistics `json:"data"`
}

// NewGetAmmPoolsStatsResponse instantiates a new GetAmmPoolsStatsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAmmPoolsStatsResponse(resultInfo ResultInfo, data []AmmPoolStatistics) *GetAmmPoolsStatsResponse {
	this := GetAmmPoolsStatsResponse{}
	this.ResultInfo = resultInfo
	this.Data = data
	return &this
}

// NewGetAmmPoolsStatsResponseWithDefaults instantiates a new GetAmmPoolsStatsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAmmPoolsStatsResponseWithDefaults() *GetAmmPoolsStatsResponse {
	this := GetAmmPoolsStatsResponse{}
	return &this
}

// GetResultInfo returns the ResultInfo field value
func (o *GetAmmPoolsStatsResponse) GetResultInfo() ResultInfo {
	if o == nil {
		var ret ResultInfo
		return ret
	}

	return o.ResultInfo
}

// GetResultInfoOk returns a tuple with the ResultInfo field value
// and a boolean to check if the value has been set.
func (o *GetAmmPoolsStatsResponse) GetResultInfoOk() (*ResultInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultInfo, true
}

// SetResultInfo sets field value
func (o *GetAmmPoolsStatsResponse) SetResultInfo(v ResultInfo) {
	o.ResultInfo = v
}

// GetData returns the Data field value
func (o *GetAmmPoolsStatsResponse) GetData() []AmmPoolStatistics {
	if o == nil {
		var ret []AmmPoolStatistics
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetAmmPoolsStatsResponse) GetDataOk() ([]AmmPoolStatistics, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetAmmPoolsStatsResponse) SetData(v []AmmPoolStatistics) {
	o.Data = v
}

func (o GetAmmPoolsStatsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["resultInfo"] = o.ResultInfo
	}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetAmmPoolsStatsResponse struct {
	value *GetAmmPoolsStatsResponse
	isSet bool
}

func (v NullableGetAmmPoolsStatsResponse) Get() *GetAmmPoolsStatsResponse {
	return v.value
}

func (v *NullableGetAmmPoolsStatsResponse) Set(val *GetAmmPoolsStatsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAmmPoolsStatsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAmmPoolsStatsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAmmPoolsStatsResponse(val *GetAmmPoolsStatsResponse) *NullableGetAmmPoolsStatsResponse {
	return &NullableGetAmmPoolsStatsResponse{value: val, isSet: true}
}

func (v NullableGetAmmPoolsStatsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAmmPoolsStatsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
