/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// GetUserFeeRates2Request struct for GetUserFeeRates2Request
type GetUserFeeRates2Request struct {
	// Account ID
	AccountId int64 `json:"accountId"`
	// Market symbol
	Market string `json:"market"`
	// Token ID
	TokenB int32 `json:"tokenB"`
	// Amount to buy
	AmountB string `json:"amountB"`
}

// NewGetUserFeeRates2Request instantiates a new GetUserFeeRates2Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserFeeRates2Request(accountId int64, market string, tokenB int32, amountB string) *GetUserFeeRates2Request {
	this := GetUserFeeRates2Request{}
	this.AccountId = accountId
	this.Market = market
	this.TokenB = tokenB
	this.AmountB = amountB
	return &this
}

// NewGetUserFeeRates2RequestWithDefaults instantiates a new GetUserFeeRates2Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserFeeRates2RequestWithDefaults() *GetUserFeeRates2Request {
	this := GetUserFeeRates2Request{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *GetUserFeeRates2Request) GetAccountId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *GetUserFeeRates2Request) GetAccountIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *GetUserFeeRates2Request) SetAccountId(v int64) {
	o.AccountId = v
}

// GetMarket returns the Market field value
func (o *GetUserFeeRates2Request) GetMarket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Market
}

// GetMarketOk returns a tuple with the Market field value
// and a boolean to check if the value has been set.
func (o *GetUserFeeRates2Request) GetMarketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Market, true
}

// SetMarket sets field value
func (o *GetUserFeeRates2Request) SetMarket(v string) {
	o.Market = v
}

// GetTokenB returns the TokenB field value
func (o *GetUserFeeRates2Request) GetTokenB() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokenB
}

// GetTokenBOk returns a tuple with the TokenB field value
// and a boolean to check if the value has been set.
func (o *GetUserFeeRates2Request) GetTokenBOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenB, true
}

// SetTokenB sets field value
func (o *GetUserFeeRates2Request) SetTokenB(v int32) {
	o.TokenB = v
}

// GetAmountB returns the AmountB field value
func (o *GetUserFeeRates2Request) GetAmountB() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmountB
}

// GetAmountBOk returns a tuple with the AmountB field value
// and a boolean to check if the value has been set.
func (o *GetUserFeeRates2Request) GetAmountBOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountB, true
}

// SetAmountB sets field value
func (o *GetUserFeeRates2Request) SetAmountB(v string) {
	o.AmountB = v
}

func (o GetUserFeeRates2Request) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	if true {
		toSerialize["market"] = o.Market
	}
	if true {
		toSerialize["tokenB"] = o.TokenB
	}
	if true {
		toSerialize["amountB"] = o.AmountB
	}
	return json.Marshal(toSerialize)
}

type NullableGetUserFeeRates2Request struct {
	value *GetUserFeeRates2Request
	isSet bool
}

func (v NullableGetUserFeeRates2Request) Get() *GetUserFeeRates2Request {
	return v.value
}

func (v *NullableGetUserFeeRates2Request) Set(val *GetUserFeeRates2Request) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserFeeRates2Request) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserFeeRates2Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserFeeRates2Request(val *GetUserFeeRates2Request) *NullableGetUserFeeRates2Request {
	return &NullableGetUserFeeRates2Request{value: val, isSet: true}
}

func (v NullableGetUserFeeRates2Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserFeeRates2Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
