/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// DepositDataList DepositDataList
type DepositDataList struct {
	// Total number of records found
	TotalNum int64 `json:"totalNum"`
	// List of DepositRecord
	Transactions []DepositData `json:"transactions"`
}

// NewDepositDataList instantiates a new DepositDataList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDepositDataList(totalNum int64, transactions []DepositData) *DepositDataList {
	this := DepositDataList{}
	this.TotalNum = totalNum
	this.Transactions = transactions
	return &this
}

// NewDepositDataListWithDefaults instantiates a new DepositDataList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDepositDataListWithDefaults() *DepositDataList {
	this := DepositDataList{}
	return &this
}

// GetTotalNum returns the TotalNum field value
func (o *DepositDataList) GetTotalNum() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalNum
}

// GetTotalNumOk returns a tuple with the TotalNum field value
// and a boolean to check if the value has been set.
func (o *DepositDataList) GetTotalNumOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalNum, true
}

// SetTotalNum sets field value
func (o *DepositDataList) SetTotalNum(v int64) {
	o.TotalNum = v
}

// GetTransactions returns the Transactions field value
func (o *DepositDataList) GetTransactions() []DepositData {
	if o == nil {
		var ret []DepositData
		return ret
	}

	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value
// and a boolean to check if the value has been set.
func (o *DepositDataList) GetTransactionsOk() ([]DepositData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transactions, true
}

// SetTransactions sets field value
func (o *DepositDataList) SetTransactions(v []DepositData) {
	o.Transactions = v
}

func (o DepositDataList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["totalNum"] = o.TotalNum
	}
	if true {
		toSerialize["transactions"] = o.Transactions
	}
	return json.Marshal(toSerialize)
}

type NullableDepositDataList struct {
	value *DepositDataList
	isSet bool
}

func (v NullableDepositDataList) Get() *DepositDataList {
	return v.value
}

func (v *NullableDepositDataList) Set(val *DepositDataList) {
	v.value = val
	v.isSet = true
}

func (v NullableDepositDataList) IsSet() bool {
	return v.isSet
}

func (v *NullableDepositDataList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDepositDataList(val *DepositDataList) *NullableDepositDataList {
	return &NullableDepositDataList{value: val, isSet: true}
}

func (v NullableDepositDataList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDepositDataList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
