/*
LightCone 2.0 API Documentation

LightCone DEX function interpretation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loopring

import (
	"encoding/json"
)

// GetExchangeInfoResponse struct for GetExchangeInfoResponse
type GetExchangeInfoResponse struct {
	ResultInfo ResultInfo    `json:"resultInfo"`
	Data       *ExchangeInfo `json:"data,omitempty"`
}

// NewGetExchangeInfoResponse instantiates a new GetExchangeInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetExchangeInfoResponse(resultInfo ResultInfo) *GetExchangeInfoResponse {
	this := GetExchangeInfoResponse{}
	this.ResultInfo = resultInfo
	return &this
}

// NewGetExchangeInfoResponseWithDefaults instantiates a new GetExchangeInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetExchangeInfoResponseWithDefaults() *GetExchangeInfoResponse {
	this := GetExchangeInfoResponse{}
	return &this
}

// GetResultInfo returns the ResultInfo field value
func (o *GetExchangeInfoResponse) GetResultInfo() ResultInfo {
	if o == nil {
		var ret ResultInfo
		return ret
	}

	return o.ResultInfo
}

// GetResultInfoOk returns a tuple with the ResultInfo field value
// and a boolean to check if the value has been set.
func (o *GetExchangeInfoResponse) GetResultInfoOk() (*ResultInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultInfo, true
}

// SetResultInfo sets field value
func (o *GetExchangeInfoResponse) SetResultInfo(v ResultInfo) {
	o.ResultInfo = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetExchangeInfoResponse) GetData() ExchangeInfo {
	if o == nil || o.Data == nil {
		var ret ExchangeInfo
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeInfoResponse) GetDataOk() (*ExchangeInfo, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetExchangeInfoResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given ExchangeInfo and assigns it to the Data field.
func (o *GetExchangeInfoResponse) SetData(v ExchangeInfo) {
	o.Data = &v
}

func (o GetExchangeInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["resultInfo"] = o.ResultInfo
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetExchangeInfoResponse struct {
	value *GetExchangeInfoResponse
	isSet bool
}

func (v NullableGetExchangeInfoResponse) Get() *GetExchangeInfoResponse {
	return v.value
}

func (v *NullableGetExchangeInfoResponse) Set(val *GetExchangeInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetExchangeInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetExchangeInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetExchangeInfoResponse(val *GetExchangeInfoResponse) *NullableGetExchangeInfoResponse {
	return &NullableGetExchangeInfoResponse{value: val, isSet: true}
}

func (v NullableGetExchangeInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetExchangeInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
